### ISSUE TITLE
Don't see sunrise and sunset in EVE App

### ISSUE THREAD

**Issue by DoWenzl94** [naofireblade/homebridge-weather-plus#197] opened 2021-04-02 17:52 UTC
Hi I get for my city Innsbruck,AT also the data for  "sunrise":1617339069, and "sunset":1617385466} but I can't see them in the EVE app. Sunset and Sunrise isn't hidden.

**Comment by dacarson** [comment] 2024-04-30 00:20
I do realize that this is an old report, but sunrise and sunset should be fixed in the latest beta.

**Comment by dacarson** [comment] 2024-04-30 00:27
Duplicate of #240

**Comment by dacarson** [comment] 2024-04-30 00:28
Closing as this is resolved.

**Closed by dacarson** 2024-04-30 00:28 UTC
Labels: Fixed - Waiting for feedback
