### ISSUE TITLE
util._extend API deprecated & punycode module deprecated

### ISSUE THREAD

**Issue by kskenyon** [naofireblade/homebridge-weather-plus#303] opened 2024-11-24 01:04 UTC
[11/24/2024, 12:53:42 AM] [@danimal4326/homebridge-weather-plus] This plugin generated a warning from the characteristic 'Current Ambient Light Level': Characteristic not in required or optional characteristic section for service TemperatureSensor. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
(node:1189266) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1189266) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

**Comment by dacarson** [comment] 2024-12-04 20:02
Tracking adding Characteristic issue here: #206 
Request module is deprecated: #150 

The other two sound new:
1. (node:1189266) [DEP0060] DeprecationWarning: The util._extend API is deprecated. Please use Object.assign() instead.
(Use node --trace-deprecation ... to show where the warning was created)
2. (node:1189266) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.

Will use this ticket to track the two new issues.

**Comment by dacarson** [comment] 2024-12-04 21:10
Added the trace-deprecation flag and it says the `psl`? module is using it:
```
(node:901683) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:112:7)
    at Function._load (node:internal/modules/cjs/loader:1100:17)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-weather-plus/node_modules/psl/index.js:5:16)

**Comment by kskenyon** [comment] 2024-12-04 21:35
https://www.npmjs.com/package/psl￼
psl
npmjs.com

**Comment by kskenyon** [comment] 2024-12-04 21:46
https://github.com/mathiasbynens/punycode.js/issues/137￼
Update README to instruct how to alias the native one (due to Node 22 annoying warning) · Issue #137 · mathiasbynens/punycode.js
github.com

**Comment by dacarson** [comment] 2024-12-04 22:16
Thank you!

**Comment by dacarson** [comment] 2024-12-04 22:32
The instructions [mathiasbynens/punycode.js#137](https://github.com/mathiasbynens/punycode.js/issues/137)￼ fix the puny code warning.

I am unable to reproduce this warning:
(node:1189266) [DEP0060] DeprecationWarning: The util._extend API is deprecated. Please use Object.assign() instead.
(Use node --trace-deprecation ... to show where the warning was created)

**Comment by dacarson** [comment] 2024-12-05 00:09
I am still not able to reproduce the warning, however, I think I found where the issue is. 
In utils/characteristics.js there is this pattern:
```
const underscore = require('underscore');
...

	let rainfallProps = (max) =>
	{
		var range = (units !== 'imperial') ? {unit: 'mm', maxValue: max, minValue: 0, minStep: 0.1}
			: {unit: 'in', maxValue: Math.round(max / 25.4), minValue: 0, minStep: 0.01};

		return underscore.extend(
			{
				format: Characteristic.Formats.FLOAT
				, perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
			}, range);
	};
```
I believe it is coming from `return underscore.extend()`

It is mentioned here https://github.com/Unitech/pm2/issues/5238 :

> Reference: https://nodejs.org/api/util.html#util_extendtarget-source
> The util._extend() method was never intended to be used outside of internal Node.js modules. There are some modules in pm2 still using this method, and it is hereafter suggested to be replaced.

**Comment by dacarson** [comment] 2024-12-05 02:00
I have submitted a fix for this.

**Closed** 2024-12-05 02:21 UTC
