### ISSUE TITLE
Warnings from characteristic

### ISSUE THREAD

**Issue by ajburnett104** [naofireblade/homebridge-weather-plus#194] opened 2021-03-30 13:12 UTC
Getting repeated errors for several parameters. Example:

`[3/30/2021, 9:02:16 AM] [homebridge-weather-plus] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.`

Should I have more info that what I see here?

![8AE93A06-E0CA-4E78-89BF-5104D32F8D37](https://user-images.githubusercontent.com/25163774/112994189-fdaaf380-9137-11eb-83c7-f85676c28bb4.jpeg)

I am using my own API for wx station KMADANVE14 (my pws). 

Thanks for your insights.

**Comment by dacarson** [comment] 2024-05-08 16:39
The problem is that you have told the plugin that you will provide the `reportCharacteristics` with a `Humidity`, but you are not setting the value. Left unset, it will be `null`. The value should be set during the call to `update()`. When HomeKit updates all the values, it updates that characteristic with null, which is not valid. HomeKit will just ignore it. 
This should be fixed in your API code.

**Closed by dacarson** 2024-05-08 16:39 UTC
Labels: Needs more info
