### ISSUE TITLE
UV index is always 0

### ISSUE THREAD

**Issue by HomebridgeX** [naofireblade/homebridge-weather-plus#264] opened 2023-05-30 07:55 UTC
Hello,
I use OpenWeatherMap and my UV index is always 0, although the weather station provides a correct value.
I use the Eve (with grouping) compatibility.

Thanks

**Comment by janni2607** [comment] 2023-06-05 07:35
I have the same problem

**Comment by dacarson** [comment] 2023-09-21 00:06
Are there any logs produced? 

Looking at the code, it seems that UVIndex and DewPoint are handled specially. So is DewPoint also an issue?

**Comment by janni2607** [comment] 2023-09-21 09:34
Yes, the dew point always shows -50 degrees C.

**Comment by jkreileder** [comment] 2024-01-18 16:14
See https://github.com/naofireblade/homebridge-weather-plus/issues/274#issuecomment-1898786420

**Comment by dacarson** [comment] 2024-01-18 20:24
Active work on this issue is in #274, 
Duplicate of #274

**Comment by dacarson** [comment] 2024-03-20 01:43
Closing as a duplicate of #274 
This report is older, however, active discussion is happening in #274

**Closed by dacarson** 2024-03-20 01:43 UTC
