### ISSUE TITLE
npm WARN deprecated ... request has been deprecated

### ISSUE THREAD

**Issue by RCdiy** [naofireblade/homebridge-weather-plus#150] opened 2020-06-30 19:34 UTC
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated text-encoding@0.6.4: no longer maintained

Using
web ui 
homebridge pi sd card image

![Screen Shot 2020-06-30 at 3 30 55 PM](https://user-images.githubusercontent.com/20209851/86168964-e2e31a00-bae6-11ea-9831-231d30ab7f37.png)

**Comment by rcoleman8806** [comment] 2020-07-01 02:30
Also just hit this issue when installing

**Comment by sriv-anant21** [comment] 2020-07-06 16:33
getting same issue

**Comment by mbierman** [comment] 2020-07-14 07:13
Confirmed here too.

**Comment by Nisse57** [comment] 2020-09-27 09:14
getting same issue

**Comment by Pelagious** [comment] 2020-12-01 05:17
Same

**Comment by barnwern** [comment] 2021-01-01 11:50
Has this been resolved - cannot install the Weather plus plugin in HOOBS?

**Comment by mkellsy** [comment] 2021-05-18 14:01
https://github.com/request/request/issues/3142

**Comment by daydy16** [comment] 2021-08-02 17:59
Had the same issue when installing via the ui.
I fixed it by installing via command line (docker exec ...) and then it showed my the real error message.
After running: "`npm install --save **--force** homebridge-weather-plus@latest`" it works for me

**Comment by mkellsy** [comment] 2021-08-03 03:50
I have looked into this. The **geo-tz** module is very large and takes a long time to download especially on slower connections.

If you modify these files;
apis/openweathermap.js
apis/yahoo.js

And use the moment-timezone module that's already included in this project. This would allow you to remove the geo-tz dependency and make this a much smaller plugin.

The only downside of this would be you can only get the time zone of the local device. Or you can add a time zone setting in the config to override.

**Comment by dacarson** [comment] 2024-12-06 23:40
Testing performed:

**Comment by dacarson** [comment] 2024-12-06 23:50
Closing as fixed

**Closed by dacarson** 2024-12-06 23:50 UTC
