### ISSUE TITLE
Openweather map dew point and UV index

### ISSUE THREAD

**Issue by sunburntandblonde** [naofireblade/homebridge-weather-plus#274] opened 2023-09-27 00:28 UTC
Weather plus dew point is showing as -50c and UV index as 0  for both current conditions and forecast, which is different from the data it should be from openweathermap. (Openweather map shows an actual dew point of 6c and UV of 0)
There is nothing (that I can see) in the logs to indicate a problem. All other data correlates and is showing correctly.

**Comment by Churro-blaze** [comment] 2023-11-08 08:28
I have the same issue. The UV is the only thing I want so I can send an alert when it gets over 6 to put sunblock on the kids. I hope someone can work it out.

**Comment by dacarson** [comment] 2023-12-28 03:51
Please attach logs

**Comment by dacarson** [comment] 2024-01-11 21:34
This seems to be the same issue as #264

**Comment by dacarson** [comment] 2024-01-16 22:41
Duplicate of #264

**Comment by jkreileder** [comment] 2024-01-18 16:12
This seems to depend on whether you have a paid subscription for the 3.0 API.
If you don't, the plugin falls back to use `/data/2.5/weather` instead of `/data/3.0/onecall` - and `/data/2.5/weather` doesn't have dew point and UV index.

The real question here is weather the 3.0 Onecall API is really needed here at all. `/data/2.5/onecall` seems to provide virtually the same data in the same structure.  (See [3.0](https://openweathermap.org/api/one-call-3) and [2.5](https://openweathermap.org/api/one-call-api) docs).

This change makes dew point and UV index work for me.  (That is, the whole 2.5 legacy code probably can be removed):

```diff
diff --git a/apis/openweathermap.js b/apis/openweathermap.js
index 9341d04..f1f0894 100644
--- a/apis/openweathermap.js
+++ b/apis/openweathermap.js
@@ -459,7 +459,7 @@ class OpenWeatherMapAPI
                }
                else
                {
-                       return this.apiBaseURL + "/data/3.0/onecall"
+                       return this.apiBaseURL + "/data/2.5/onecall"
                }
        }
```

**Comment by jkreileder** [comment] 2024-01-18 22:19
Now for the bad news: Apparently `2.5/onecall` is disabled for newer accounts (see https://github.com/domoticz/domoticz/issues/5336#issuecomment-1243023845). So the only real solution for dew point and UV index is to get a base subscription, so that you can use `3.0/onecall`: Basically enter payment details, then set a limit so you don't ever get over the 1000 free calls.

**Comment by dacarson** [comment] 2024-01-19 02:21
To stop Dew Point and UV index from appearing when 2.5 API is used, there is code tries to remove it from the reported characteristics:
```
	that.log.info("Could not retreive weather report with API 3.0, trying API 2.5 now ...")
	this.api = "2.5";
	this.removeCharacteristic(this.reportCharacteristics, "UVIndex");
	this.removeCharacteristic(this.reportCharacteristics, "DewPoint");
	this.removeCharacteristic(this.forecastCharacteristics, "UVIndex");
	this.removeCharacteristic(this.forecastCharacteristics, "DewPoint");
	this.removeCharacteristic(this.forecastCharacteristics, "SunriseTime");
	this.removeCharacteristic(this.forecastCharacteristics, "SunsetTime");
	this.forecastDays = 5;
```
The code for removeCharacteristic() is later in the same file:
```
	removeCharacteristic(characteristics, item)
	{
		let index = characteristics.indexOf(item);
		if (index !== -1)
		{
			characteristics.splice(index, 1);
		}
	}
```

Which just removes it from the array of data that is reported. Unfortunately, by this time the characteristic has already been added by the function `CurrentConditionsWeatherAccessory()` as a Characteristic of the Accessory. So the effect that the `removeCharacteristic()` function has is to always fail to report that value.

**Comment by dacarson** [comment] 2024-01-19 02:34
As the data simply isn't available to the 2.5 API, the user can just go the plugin settings, expand the 'Hide values' section and check UV Index, Dew Point, Sunrise Time and Sunset Time. Then those items won't appear in HomeKit.

A possible programatic solution is lazily add the Characteristics. If, when updating that weather data, the Accessory is missing the Characteristic for a given `reportCharacteristics` name, then create and add it on the fly. (Or remove it on the fly - though this would be more work IMO)
In this scenario, UV, Dewpoint, SunriseTime and SunsetTime would be added to the list of `reportCharacteristics` only when the 3.0 API availability is confirmed.

**Comment by dacarson** [comment] 2024-03-26 19:49
Can you please try `3.3.4-beta.1` and verify that it works.

**Comment by dacarson** [comment] 2024-05-08 16:22
Closing as fixed. Try `3.3.4` or later

**Closed by dacarson** 2024-05-08 16:22 UTC
Labels: Fixed - Waiting for feedback
